# Generated by Django 5.1.6 on 2025-06-30 20:20

import utils.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='national_code',
            field=models.IntegerField(blank=True, null=True, validators=[utils.validator.persian_national_code]),
        ),
    ]
