# Generated by Django 5.1.6 on 2025-07-26 21:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_otp_options_remove_otp_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otp',
            options={'verbose_name': 'رمز یکبار مصرف', 'verbose_name_plural': ' احراز هویت Otp'},
        ),
        migrations.AlterField(
            model_name='otp',
            name='code_expiry',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 26, 21, 12, 58, 499475, tzinfo=datetime.timezone.utc), verbose_name='تاریخ انقضای کد'),
        ),
    ]
