# Generated by Django 5.1.6 on 2025-06-08 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expiration_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
