# Generated by Django 5.1.6 on 2025-06-25 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_user_password'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otp',
            options={'verbose_name_plural': 'یکبار مصرف '},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': 'کاربران'},
        ),
        migrations.AlterField(
            model_name='otp',
            name='code',
            field=models.SmallIntegerField(verbose_name='کد یکبار مصرف'),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expiration_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='مدت زمان اعتبار کد'),
        ),
        migrations.AlterField(
            model_name='otp',
            name='phone',
            field=models.CharField(max_length=11, verbose_name='شماره تلفن'),
        ),
        migrations.AlterField(
            model_name='otp',
            name='token',
            field=models.CharField(max_length=200, null=True, verbose_name='توکن'),
        ),
    ]
