# Generated by Django 5.1.6 on 2025-06-26 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_otp_options_alter_user_options_alter_otp_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='آخرین ورود'),
        ),
    ]
