# Generated by Django 5.1.6 on 2025-06-26 14:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_user_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='expiration_date',
        ),
        migrations.AddField(
            model_name='otp',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=1, verbose_name='تاریخ ایجاد'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otp',
            name='expiry_minutes',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='مدت زمان اعتبار'),
        ),
        migrations.AlterField(
            model_name='otp',
            name='phone',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='شماره تلفن باید با 09 شروع شده و 11 رقمی باشد', regex='^09\\d{9}$')], verbose_name='شماره تلفن'),
        ),
    ]
