# Generated by Django 5.1.6 on 2025-06-26 15:10

import utils.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_remove_otp_expiration_date_otp_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expiry_minutes',
            field=models.IntegerField(default=2, verbose_name='مدت زمان اعتبار'),
        ),
        migrations.AlterField(
            model_name='otp',
            name='phone',
            field=models.CharField(max_length=11, validators=[utils.validator.persian_phone_number_validation], verbose_name='شماره تلفن'),
        ),
    ]
