# Generated by Django 5.1.6 on 2025-07-21 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_about_me_alter_sitesettings_text_about_us'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about_me',
            options={'verbose_name': 'درباره ما', 'verbose_name_plural': 'درباره ما'},
        ),
    ]
