# Generated by Django 5.1.6 on 2025-07-28 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashbord', '0003_alter_favorites_options_alter_favorites_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=50, verbose_name='استان'),
        ),
    ]
