# Generated by Django 5.1.6 on 2025-07-30 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashbord', '0005_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
