# Generated by Django 5.2.3 on 2025-06-22 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='عنوان')),
                ('image', models.ImageField(upload_to='product/image', verbose_name='بارگذاری تصویر')),
                ('price', models.SmallIntegerField(verbose_name='قیمت')),
                ('value', models.SmallIntegerField(verbose_name='مقدار')),
            ],
            options={
                'verbose_name_plural': 'محصولات',
            },
        ),
    ]
