# Generated by Django 5.2.3 on 2025-06-22 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='Category',
            field=models.ManyToManyField(related_name='Category', to='Products.category'),
        ),
    ]
