# Generated by Django 5.1.6 on 2025-07-09 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_category_views_alter_products_image_subset_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category/image', verbose_name='تصویر دسته بندی'),
        ),
        migrations.AlterField(
            model_name='category',
            name='views',
            field=models.BooleanField(default=False, verbose_name='نمایش در صحفه اصلی '),
        ),
    ]
