# Generated by Django 5.2.3 on 2025-06-24 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_color_size_products_color_products_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'برند ها ',
            },
        ),
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name_plural': 'رنگ بندی '},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'verbose_name_plural': 'سایز'},
        ),
    ]
