# Generated by Django 5.2.3 on 2025-06-24 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_brand_alter_color_options_alter_size_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='title',
            field=models.CharField(max_length=60, verbose_name='برند'),
        ),
        migrations.AlterField(
            model_name='color',
            name='title',
            field=models.CharField(max_length=30, verbose_name='عنوان رنگ'),
        ),
        migrations.AlterField(
            model_name='products',
            name='Category',
            field=models.ManyToManyField(related_name='Category', to='Products.category', verbose_name='دسته بندی ها'),
        ),
        migrations.AlterField(
            model_name='products',
            name='color',
            field=models.ManyToManyField(related_name='product', to='Products.color', verbose_name='رنگ بندی ها'),
        ),
        migrations.AlterField(
            model_name='products',
            name='size',
            field=models.ManyToManyField(blank=True, null=True, related_name='product', to='Products.size', verbose_name='سایز'),
        ),
        migrations.AlterField(
            model_name='size',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
