# Generated by Django 5.1.6 on 2025-07-11 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0006_alter_information_options_alter_products_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='slug',
        ),
    ]
