# Generated by Django 5.2.3 on 2025-06-24 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0007_comment'),
        ('account', '0010_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(verbose_name='نظر'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='Products.comment', verbose_name='پاسخ ها '),
        ),
        migrations.AlterField(
            model_name='comment',
            name='products',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Products.products', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='account.user', verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='products',
            name='size',
            field=models.ManyToManyField(blank=True, related_name='product', to='Products.size', verbose_name='سایز'),
        ),
    ]
