# Generated by Django 5.1.6 on 2025-06-26 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0008_alter_comment_body_alter_comment_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='title',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='برند'),
        ),
        migrations.AlterField(
            model_name='color',
            name='title',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='عنوان رنگ'),
        ),
        migrations.AlterField(
            model_name='products',
            name='size',
            field=models.ManyToManyField(blank=True, related_name='product', to='Products.size'),
        ),
    ]
