# Generated by Django 5.1.6 on 2025-06-27 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0009_alter_brand_title_alter_color_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='caption',
            field=models.TextField(default=1, verbose_name='درباره محصول'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='hover_title',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='عنوان معرفی'),
        ),
        migrations.AlterField(
            model_name='products',
            name='title',
            field=models.CharField(max_length=80, verbose_name='عنوان'),
        ),
    ]
