# Generated by Django 5.1.6 on 2025-06-27 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0010_products_caption_products_hover_title_and_more'),
        ('account', '0014_alter_otp_expiry_minutes_alter_otp_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='inventory',
            field=models.BooleanField(default=True, verbose_name='موجودیت'),
        ),
        migrations.AddField(
            model_name='products',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='به صورت خودکار از عنوان محصول استفاده میشود'),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='Products.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='account.user')),
            ],
            options={
                'verbose_name': 'پسند',
                'verbose_name_plural': 'پسند ها',
                'ordering': ('-created_at',),
            },
        ),
    ]
