# Generated by Django 5.1.6 on 2025-06-27 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0011_products_inventory_products_slug_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='به صورت خودکار از عنوان محصول استفاده میشود'),
        ),
    ]
