# Generated by Django 5.1.6 on 2025-07-26 21:18

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0012_alter_color_color_code_alter_color_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='temp-slug', editable=False, populate_from='title', unique=True),
        ),
        migrations.AddField(
            model_name='products',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='temp-slug', editable=False, populate_from='title', unique=True),
        ),
    ]
