# Generated by Django 5.1.6 on 2025-06-27 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0012_alter_products_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='Category',
        ),
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Products.category', verbose_name='دسته بندی'),
        ),
    ]
