# Generated by Django 5.1.6 on 2025-07-28 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0015_remove_category_slug_remove_products_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
