# Generated by Django 5.1.6 on 2025-08-02 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0021_remove_products_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='slug',
            field=models.SlugField(blank=True, help_text='مقدار به صورت خودکار از عنوان محصول استلفاده می شود', unique=True, verbose_name='نامک'),
        ),
    ]
