# Generated by Django 5.2.3 on 2025-06-24 13:02

import account.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0010_alter_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان رسانه')),
            ],
        ),
        migrations.CreateModel(
            name='Utm_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utm_source', models.CharField(max_length=200, verbose_name='منبع ورودی ')),
                ('utm_medium', models.CharField(max_length=200, verbose_name='رسانه')),
                ('utm_campaign', models.CharField(max_length=200, verbose_name='کمپین')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('base_url', models.URLField()),
                ('full_url', models.URLField(blank=True)),
                ('platform', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Social.platform')),
            ],
        ),
        migrations.CreateModel(
            name='Utm_access',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_admin', models.CharField(verbose_name=account.models.User)),
                ('access_level', models.CharField()),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('utm_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Social.utm_info')),
            ],
        ),
        migrations.CreateModel(
            name='Log_Utm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_sale', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.user')),
                ('platform', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Social.platform')),
                ('url', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Social.utm_info')),
            ],
        ),
    ]
