# Generated by Django 5.2.3 on 2025-06-24 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Social', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log_utm',
            options={'verbose_name_plural': 'گزاشات لینک ها '},
        ),
        migrations.AlterModelOptions(
            name='platform',
            options={'verbose_name_plural': 'مدیریت رسانه ها'},
        ),
        migrations.AlterModelOptions(
            name='utm_access',
            options={'verbose_name_plural': 'سطح دسترسی به لینک ها '},
        ),
        migrations.AlterModelOptions(
            name='utm_info',
            options={'verbose_name_plural': 'مدیریت لینک ها'},
        ),
        migrations.AddField(
            model_name='log_utm',
            name='views',
            field=models.IntegerField(default=1, verbose_name='بازدید ها'),
            preserve_default=False,
        ),
    ]
