# Generated by Django 5.2.3 on 2025-06-24 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Social', '0002_alter_log_utm_options_alter_platform_options_and_more'),
        ('account', '0010_alter_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utm_info',
            name='full_url',
        ),
        migrations.AddField(
            model_name='utm_info',
            name='sharing_url',
            field=models.URLField(blank=True, verbose_name='لینک اشتراک گذاری'),
        ),
        migrations.AlterField(
            model_name='log_utm',
            name='platform',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Social.platform', verbose_name='عنوان رسانه'),
        ),
        migrations.AlterField(
            model_name='log_utm',
            name='url',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Social.utm_info', verbose_name='لینک رسانه'),
        ),
        migrations.AlterField(
            model_name='log_utm',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.user', verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='utm_info',
            name='base_url',
            field=models.URLField(verbose_name='لینک اصلی'),
        ),
        migrations.AlterField(
            model_name='utm_info',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
    ]
