# Generated by Django 5.2.3 on 2025-06-24 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Social', '0003_remove_utm_info_full_url_utm_info_sharing_url_and_more'),
        ('account', '0010_alter_user_password'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log_utm',
            options={'verbose_name_plural': 'گزاشات '},
        ),
        migrations.RemoveField(
            model_name='log_utm',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='log_utm',
            name='is_sale',
        ),
        migrations.RemoveField(
            model_name='log_utm',
            name='user',
        ),
        migrations.AlterField(
            model_name='utm_access',
            name='access_level',
            field=models.CharField(verbose_name='سطح دسترسی کاریر '),
        ),
        migrations.AlterField(
            model_name='utm_access',
            name='granted_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ اعطای دسترسی'),
        ),
        migrations.AlterField(
            model_name='utm_access',
            name='user_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.user', verbose_name='انتخاب کاربر ادمین'),
        ),
        migrations.AlterField(
            model_name='utm_access',
            name='utm_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Social.utm_info', verbose_name='لینک های قابل دسترس'),
        ),
    ]
