# Generated by Django 5.2.3 on 2025-06-24 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Social', '0004_alter_log_utm_options_remove_log_utm_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utm_access',
            name='access_level',
            field=models.BooleanField(verbose_name='سطح دسترسی کاریر '),
        ),
    ]
