# Generated by Django 5.2.3 on 2025-06-24 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Social', '0005_alter_utm_access_access_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log_utm',
            options={'verbose_name_plural': 'گزارشات '},
        ),
        migrations.AddField(
            model_name='log_utm',
            name='cart',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='log_utm',
            name='views',
            field=models.SmallIntegerField(verbose_name='بازدید ها'),
        ),
    ]
