# Generated by Django 5.1.6 on 2025-06-25 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Social', '0006_alter_log_utm_options_log_utm_cart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='platform_type',
            field=models.CharField(choices=[('instagram', 'Instagram'), ('telegram', 'Telegram'), ('whatsapp', 'Whatsapp')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='utm_access',
            name='access_level',
            field=models.CharField(choices=[('view', 'مشاهده'), ('edit', 'ویرایش')], max_length=30, verbose_name='سطح دسترسی کاریر '),
        ),
    ]
