# Generated by Django 5.1.6 on 2025-06-25 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Social', '0007_platform_platform_type_alter_utm_access_access_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='title',
            field=models.CharField(max_length=50, unique=True, verbose_name='عنوان رسانه'),
        ),
    ]
