# Generated by Django 5.1.6 on 2025-06-25 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Social', '0008_alter_platform_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platform',
            name='platform_type',
        ),
        migrations.AlterField(
            model_name='platform',
            name='title',
            field=models.CharField(choices=[('instagram', 'اینستاگرام'), ('telegram', 'تلگرام'), ('whatsapp', 'واتساپ')], max_length=20),
        ),
    ]
