# Generated by Django 5.1.6 on 2025-06-25 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Social', '0010_alter_platform_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='title',
            field=models.CharField(choices=[('اینستاگرام', 'Instagram'), ('تلگرام', 'Telegram'), ('واتساپ', 'Whatsapp')], max_length=20, verbose_name=' رسانه'),
        ),
        migrations.AlterField(
            model_name='utm_info',
            name='platform',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Social.platform', verbose_name='رسانه'),
        ),
    ]
