# Generated by Django 5.1.6 on 2025-06-25 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Social', '0011_alter_platform_title_alter_utm_info_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='Favorite_media',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='platform',
            name='title',
            field=models.CharField(blank=True, choices=[('اینستاگرام', 'Instagram'), ('تلگرام', 'Telegram'), ('واتساپ', 'Whatsapp'), ('ایتا', 'Eita'), ('روبیکا', 'Rubika')], max_length=20, null=True, verbose_name='رسانه های موجود'),
        ),
    ]
