# Generated by Django 5.1.6 on 2025-06-25 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Social', '0012_platform_favorite_media_alter_platform_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='Favorite_media',
            field=models.CharField(max_length=50, verbose_name='رسانه دلخواه'),
        ),
    ]
