# Generated by Django 5.1.6 on 2025-06-25 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Social', '0013_alter_platform_favorite_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='Favorite_media',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رسانه دلخواه'),
        ),
    ]
