# Generated by Django 5.1.6 on 2025-06-25 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Social', '0014_alter_platform_favorite_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platform',
            name='Favorite_media',
        ),
    ]
