# Generated by Django 5.1.6 on 2025-06-25 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Social', '0015_remove_platform_favorite_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='title',
            field=models.CharField(blank=True, choices=[('اینستاگرام', 'Instagram'), ('تلگرام', 'Telegram'), ('واتساپ', 'Whatsapp'), ('ایتا', 'Eita'), ('روبیکا', 'Rubika')], max_length=50, null=True, verbose_name='رسانه های موجود'),
        ),
    ]
