# Generated by Django 5.1.6 on 2025-07-20 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='text_about_us',
            field=models.TextField(blank=True, null=True, verbose_name='متن درباره ما'),
        ),
    ]
