# Generated by Django 5.1.6 on 2025-07-20 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sitesettings_title_alter_sitesettings_text_about_us'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='address',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='عنوان فروشگاه'),
        ),
    ]
