# Generated by Django 5.1.6 on 2025-08-06 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashbord', '0006_delete_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='receiver_name',
        ),
        migrations.AddField(
            model_name='address',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام تحویل گیرنده'),
        ),
        migrations.AddField(
            model_name='address',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام خانوداگی تحویل گیرنده'),
        ),
    ]
