# Generated by Django 5.1.6 on 2025-07-10 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_category_image_alter_category_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='color',
            field=models.ManyToManyField(blank=True, null=True, related_name='product', to='Products.color', verbose_name='رنگ بندی ها'),
        ),
    ]
