# Generated by Django 5.1.6 on 2025-07-26 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0014_alter_category_slug_alter_products_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='products',
            name='slug',
        ),
    ]
