# Generated by Django 5.1.6 on 2025-07-30 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0017_category_slug_products_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='views',
            field=models.BooleanField(default=True, verbose_name='نمایش در صحفه اصلی '),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
