# Generated by Django 5.1.6 on 2025-08-02 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0020_products_status_alter_comment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='status',
        ),
    ]
